Repository chef/chef-dk, pull requests merged in 2018-09, with the labels that each got.

#1687 Update to Foodcritic 14.1.0
  Gemfile.lock
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Minor Version

#1697 Use subscriptions and fix expeditor warning
  .expeditor/config.yml
Labels: Expeditor: Skip All

#1693 Update acceptance dependencies to the latest
  acceptance/Gemfile.lock
Labels: Expeditor: Exclude From Changelog

#1716 Update omnibus build deps to the latest
  omnibus/Gemfile.lock
Labels: Expeditor: Exclude From Changelog

#1727 Update chef to 13.11 + rubyzip + update other deps
  .expeditor/config.yml
  .expeditor/update_chef.sh
  .expeditor/update_dockerfile.sh
  Gemfile
  Gemfile.lock
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Minor Version

#1728 start section to collect notes for yet-to-be-released changes
  RELEASE_NOTES.md
Labels: Expeditor: Bump Minor Version
