Repository chef/chef-dk, pull requests merged in 2019-08, with the labels that each got.

#2205 [ci] Add artifactory to omnibus gemfile
  omnibus/Gemfile
  omnibus/Gemfile.lock
Labels: Expeditor: Skip All

#2206 [ci] Add artifactory to omnibus/Gemfile and update omnibus gem
  omnibus/Gemfile
  omnibus/Gemfile.lock
Labels: Expeditor: Skip All

#2202 Improve packaging Chef-DK with Habitat
  .expeditor/verify.pipeline.yml
  .gitignore
  .studiorc
  habitat/plan.sh
  habitat/scripts/ci_integration_tests.sh
  habitat/tests.sh
Labels: Aspect: Packaging, Type: Chore

#2200 Concurrently install gems in the omnibus def
  omnibus/config/software/chef-dk.rb
Labels: Aspect: Packaging, Aspect: Performance, Type: Enhancement

#2213 Minor typo fixes
  RELEASE_NOTES.md
Labels: Aspect: Documentation, Expeditor: Skip All

#2217 Add DK 4.3 release notes
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2219 Deprecate sles 11 for chefdk-3 branch
  .expeditor/release.omnibus.yml
Labels: Expeditor: Skip All

#2224 Bump inspec-bin to 4.12.0
  Gemfile.lock
Labels: Expeditor: Bump Version Minor
