Repository chef/chef-dk, pull requests merged in 2019-10, with the labels that each got.

#2278 Fix Habitat build failure
  habitat/plan.sh
Labels: Aspect: Correctness, Aspect: Packaging, Type: Bug

#2277 Fix Habitat build failure
  habitat/plan.sh
Labels: Aspect: Correctness, Aspect: Packaging, Type: Bug

#2305 Enable Habitat package promotions
  .expeditor/config.yml
Labels: Aspect: Packaging

#2303 Add ChefDK 4.4 and 4.5 release notes & bump Cookstyle
  .expeditor/verify.pipeline.yml
  Gemfile.lock
  RELEASE_NOTES.md
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Version Minor

#2307 A few last minute changes + ChefDK 3.12 release notes
  Dockerfile
  Gemfile
  Gemfile.lock
  RELEASE_NOTES.md
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Version Minor

#2182 Replace usage of deprecated Net::HTTPServerException error class
  lib/chef-dk/policyfile/uploader.rb
  lib/chef-dk/policyfile_services/rm_policy.rb
  spec/unit/policyfile/uploader_spec.rb
  spec/unit/policyfile_services/clean_policies_spec.rb
  spec/unit/service_exception_inspectors/http_spec.rb
Labels: Aspect: Stability, Type: Chore, Type: Deprecation, Type: Tech Debt
