Repository chef/chef-dk, pull requests merged in 2019-07, with the labels that each got.

#2162 Use the product constant in a few more places
  lib/chef-dk/command/shell_init.rb
  lib/chef-dk/policyfile_services/push_archive.rb
  spec/unit/policyfile_services/push_archive_spec.rb
Labels: Expeditor: Bump Version Minor

#2166 Add the DK 4.1 Release Notes
  RELEASE_NOTES.md
Labels: Expeditor: Skip Habitat, Expeditor: Skip Omnibus, Expeditor: Skip Version Bump

#2190 Add release notes for the next DK
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2189 Fix deprecated chef provision command to not fail
  lib/chef-dk/builtin_commands.rb
Labels: Expeditor: Skip Habitat, Expeditor: Skip Omnibus

#2192 Update the Azure SDK gems to the latest
  Gemfile.lock
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Version Minor

#2193 Enable RHEL 8 packages
  .expeditor/release.omnibus.yml
Labels: Expeditor: Bump Version Minor
