Repository chef/chef-dk, pull requests merged in 2019-05, with the labels that each got.

#2054 update repo to new Chef OSS practices
  README.md
  tasks/dependencies.rb
Labels: Aspect: Documentation, Expeditor: Skip All

#2076 Disable expeditor update subscriptions
  .expeditor/config.yml
Labels: Expeditor: Skip All

#2078 Update kitchen-vagrant, mixlib-cli, mixlib-install, and ohai
  Gemfile
  Gemfile.lock
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Version Minor

#2087 Fixing formatting on release notes.
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2088 Pull chefdk 3.9 and 3.10 release notes to master.
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2093 CI: avoid sudo env variable cleaning?
  ci/verify-chefdk.sh
Labels: Expeditor: Skip Changelog

#2098 Copyediting for ChefDK 4.0 release notes
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2100 ChefDK 4.x Release notes prep for promotion to stable
  .expeditor/config.yml
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2106 Adding EULA to the release notes for 4.0
  RELEASE_NOTES.md
Labels: Expeditor: Skip All

#2108 Pull in updated kitchen-dokken, chef-apply and pushy-client
  Gemfile.lock
  omnibus/Gemfile.lock
Labels: Expeditor: Bump Version Minor
