Repository chef/chef-dk, pull requests merged in 2020-07, with the labels that each got.

#2982 Remove Buildkite Pipelines
  .expeditor/config.yml
Labels: Expeditor: Skip All

#2984 Make DK3 status deprecated
  README.md
Labels: Expeditor: Skip Habitat, Expeditor: Skip Omnibus

#2983 Update project status to 'maintained'
  README.md
Labels: Expeditor: Skip Habitat, Expeditor: Skip Omnibus

#3010 Update knife-opcs to 0.4.6
  Gemfile.lock
Labels: Expeditor: Bump Version Minor

#3011 Add DK 4.10 release notes
  RELEASE_NOTES.md
Labels: Expeditor: Skip All
